const SOCKET_EVENTS = {
  LOAD_CONTACTS: "LOAD_CONTACTS",
  CONTACTS: "CONTACTS",
  LOAD_ACTIVE_CONTACT : "LOAD_ACTIVE_CONTACT",
  ACTIVE_CONTACT : "ACTIVE_CONTACT",
  LOAD_MESSAGES: "LOAD_MESSAGES",
  MESSAGES: "MESSAGES",
  SEND_MESSAGE: "SEND_MESSAGE",
  NEW_MESSAGE: "NEW_MESSAGE",
};

export default SOCKET_EVENTS


