const SOCKET_EVENTS = {
  USER_IN_OUT : "USER_IN_OUT",
  LOAD_CONTACTS: "LOAD_CONTACTS",
  CONTACTS: "CONTACTS",
  LOAD_ACTIVE_CONTACT : "LOAD_ACTIVE_CONTACT",
  ACTIVE_CONTACT : "ACTIVE_CONTACT",
  LOAD_MESSAGES: "LOAD_MESSAGES",
  MESSAGES: "MESSAGES",
  SEND_MESSAGE: "SEND_MESSAGE",
  NEW_MESSAGE: "NEW_MESSAGE",
  RELOAD_CONTACTS : "RELOAD_CONTACTS",

};

export default SOCKET_EVENTS


